# Generated by Django 5.2 on 2025-07-20 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_note_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='is_approved',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 448662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 449662, tzinfo=datetime.timezone.utc)),
        ),
    ]
