# Generated by Django 5.2 on 2025-07-07 11:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_appointment_request_date_and_more'),
        ('users', '0002_alter_volunteer_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(blank=True, max_length=50000, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 11, 9, 23, 642224, tzinfo=datetime.timezone.utc))),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.patient')),
                ('volunteer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.volunteer')),
            ],
        ),
    ]
