# Generated by Django 5.2 on 2025-07-07 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='withdrawal_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 12, 50, 55, 238610, tzinfo=datetime.timezone.utc)),
        ),
    ]
