# Generated by Django 5.2 on 2025-07-20 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_approved_withdrawalrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 355207, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 356210, tzinfo=datetime.timezone.utc)),
        ),
    ]
