# Generated by Django 5.2 on 2025-07-08 07:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteer_withdrawal_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 22, 59, 413657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField()),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 22, 59, 413657, tzinfo=datetime.timezone.utc))),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_request', to='users.volunteer')),
            ],
        ),
    ]
