# Generated by Django 5.2 on 2025-07-20 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_note_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 39, 16, 905779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 39, 16, 906782, tzinfo=datetime.timezone.utc)),
        ),
    ]
