# Generated by Django 5.2 on 2025-07-08 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_note_creation_date_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='withdrawal_requested',
        ),
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 723915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 723915, tzinfo=datetime.timezone.utc)),
        ),
    ]
