# Generated by Django 5.2 on 2025-07-08 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_note_creation_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 10, 1, 45, 519798, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 10, 1, 45, 519798, tzinfo=datetime.timezone.utc)),
        ),
    ]
