# Generated by Django 5.2 on 2025-07-07 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointment_status', models.CharField(choices=[('APP', 'Approval'), ('PEN', 'Pending'), ('REJ', 'Rejected')], default='PEN', max_length=3)),
                ('request_date', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 8, 58, 50, 875001, tzinfo=datetime.timezone.utc))),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateTimeField()),
                ('medical_report', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeathPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 8, 58, 50, 874002, tzinfo=datetime.timezone.utc))),
                ('cause_of_death', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('family_book_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('date_of_blindness', models.DateField(blank=True, null=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('other_disability', models.TextField(blank=True, null=True)),
                ('chronic_illness', models.TextField(blank=True, null=True)),
                ('requirement_of_ongoing_medication', models.TextField(blank=True, null=True)),
                ('requirement_of_special_care', models.TextField(blank=True, null=True)),
                ('residence_in_the_institution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 8, 58, 50, 873000, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 8, 58, 50, 873000, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='TransitionPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 7, 8, 58, 50, 874002, tzinfo=datetime.timezone.utc))),
                ('new_association', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
