# Generated by Django 5.2.1 on 2025-06-12 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.patient'),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.patient'),
        ),
        migrations.AddField(
            model_name='pendingpatientstatus',
            name='patientStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_statuses', to='services.patientstatus'),
        ),
        migrations.AddField(
            model_name='registrationpatientstatus',
            name='patientStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_statuses', to='services.patientstatus'),
        ),
    ]
