# Generated by Django 5.2 on 2025-07-20 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 6, 48, 239982, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 6, 48, 224981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 6, 48, 224981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 6, 48, 224981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transitionpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 6, 48, 224981, tzinfo=datetime.timezone.utc)),
        ),
    ]
