# Generated by Django 5.2.1 on 2025-06-15 13:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 13, 36, 4, 80362, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 13, 36, 4, 78361, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 15, 13, 36, 4, 79364, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DeathPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.datetime(2025, 6, 15, 13, 36, 4, 79364, tzinfo=datetime.timezone.utc))),
                ('cause_of_death', models.TextField(blank=True, max_length=200, null=True)),
                ('patientStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_statuses', to='services.patientstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.datetime(2025, 6, 15, 13, 36, 4, 79364, tzinfo=datetime.timezone.utc))),
                ('new_association', models.TextField(blank=True, max_length=200, null=True)),
                ('patientStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_statuses', to='services.patientstatus')),
            ],
        ),
    ]
