# Generated by Django 5.2 on 2025-07-20 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_appointment_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 465656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 451662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 450664, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 450664, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transitionpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 451662, tzinfo=datetime.timezone.utc)),
        ),
    ]
