# Generated by Django 5.2 on 2025-07-20 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_appointment_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 373216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 357213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 357213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 357213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transitionpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 358211, tzinfo=datetime.timezone.utc)),
        ),
    ]
