# Generated by Django 5.2 on 2025-07-08 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_appointment_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 727916, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 726916, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 725916, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 726916, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transitionpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 726916, tzinfo=datetime.timezone.utc)),
        ),
    ]
