# Generated by Django 5.2 on 2025-07-23 14:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_appointment_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 967229, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 951230, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 950228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 950228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RejectedPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 951230, tzinfo=datetime.timezone.utc))),
                ('case_of_rejection', models.TextField(blank=True, max_length=500, null=True)),
                ('patientStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_statuses', to='services.patientstatus')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalPatientStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 951230, tzinfo=datetime.timezone.utc))),
                ('new_association', models.TextField(blank=True, max_length=200, null=True)),
                ('patientStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_statuses', to='services.patientstatus')),
            ],
        ),
        migrations.DeleteModel(
            name='TransitionPatientStatus',
        ),
    ]
