# Generated by Django 5.2 on 2025-07-26 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_appointment_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_status',
            field=models.CharField(choices=[('APP', 'Approval'), ('PEN', 'Pending'), ('REJ', 'Rejected')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 12, 42, 13, 702052, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 12, 42, 13, 701051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 12, 42, 13, 701051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 12, 42, 13, 701051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rejectedpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 12, 42, 13, 701051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 12, 42, 13, 701051, tzinfo=datetime.timezone.utc)),
        ),
    ]
