# Generated by Django 5.2 on 2025-07-26 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_doctor_doctor_status_alter_appointment_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 822237, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='deathpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 820237, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pendingpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 820237, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registrationpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 820237, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rejectedpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 821236, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='withdrawalpatientstatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 820237, tzinfo=datetime.timezone.utc)),
        ),
    ]
