# Generated by Django 5.2 on 2025-07-20 07:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('donation_type', models.CharField(choices=[('ASS', 'Association'), ('IND', 'Individual')], default='ASS', max_length=3)),
                ('donation_status', models.CharField(choices=[('APP', 'Approval'), ('PEN', 'Pending'), ('REJ', 'Rejected'), ('CMP', 'Completed')], default='PEN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 7, 20, 7, 38, 1, 371637, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='PatientDonation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_donation', to='donations.donation')),
            ],
        ),
    ]
