# Generated by Django 5.2 on 2025-07-10 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 14, 47, 29, 404504, tzinfo=datetime.timezone.utc)),
        ),
    ]
