# Generated by Django 5.2 on 2025-07-20 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 6, 48, 241972, tzinfo=datetime.timezone.utc)),
        ),
    ]
