# Generated by Django 5.2 on 2025-07-11 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 20, 4, 27, 278379, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_status',
            field=models.CharField(choices=[('APP', 'Approval'), ('PEN', 'Pending'), ('REJ', 'Rejected'), ('COM', 'Completed')], default='PEN', max_length=3),
        ),
    ]
