# Generated by Django 5.2 on 2025-07-07 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 11, 9, 23, 647225, tzinfo=datetime.timezone.utc)),
        ),
    ]
