# Generated by Django 5.2.1 on 2025-06-15 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 9, 29, 646670, tzinfo=datetime.timezone.utc)),
        ),
    ]
