# Generated by Django 5.2 on 2025-07-07 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 12, 50, 55, 243613, tzinfo=datetime.timezone.utc)),
        ),
    ]
