# Generated by Django 5.2 on 2025-07-20 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 374913, tzinfo=datetime.timezone.utc)),
        ),
    ]
