# Generated by Django 5.2 on 2025-07-05 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 5, 12, 2, 19, 698523, tzinfo=datetime.timezone.utc)),
        ),
    ]
