# Generated by Django 5.2 on 2025-07-08 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 7, 57, 34, 729917, tzinfo=datetime.timezone.utc)),
        ),
    ]
