# Generated by Django 5.2 on 2025-07-08 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 9, 8, 35, 362081, tzinfo=datetime.timezone.utc)),
        ),
    ]
