# Generated by Django 5.2 on 2025-07-26 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 13, 1, 17, 823238, tzinfo=datetime.timezone.utc)),
        ),
    ]
