# Generated by Django 5.2 on 2025-07-20 07:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 7, 20, 7, 38, 1, 348631, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 7, 20, 7, 38, 1, 347634, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('mime_type', models.CharField(choices=[('image/jpeg', 'JPEG Image'), ('image/png', 'PNG Image'), ('image/gif', 'GIF Image'), ('image/webp', 'WebP Image'), ('video/mp4', 'MP4 Video'), ('video/webm', 'WebM Video'), ('video/ogg', 'Ogg Video'), ('video/x-msvideo', 'AVI Video')], max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('activitie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.activities')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.services')),
            ],
        ),
    ]
