# Generated by Django 5.2 on 2025-07-20 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_activities_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 443649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 9, 7, 46, 443649, tzinfo=datetime.timezone.utc)),
        ),
    ]
