# Generated by Django 5.2 on 2025-07-20 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_activities_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 350574, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 37, 43, 350574, tzinfo=datetime.timezone.utc)),
        ),
    ]
