# Generated by Django 5.2 on 2025-07-20 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_activities_creation_date_alter_media_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 39, 16, 900777, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 11, 39, 16, 900777, tzinfo=datetime.timezone.utc)),
        ),
    ]
