# Generated by Django 5.2 on 2025-07-21 14:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_activities_creation_date_alter_media_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='activitie',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='media',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_media', to='homepage.activities'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 14, 57, 35, 954363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activities',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_media', to='homepage.services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 14, 57, 35, 954363, tzinfo=datetime.timezone.utc)),
        ),
    ]
