# Generated by Django 5.2 on 2025-07-23 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_media_activitie_remove_media_mime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 944223, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 14, 27, 4, 943224, tzinfo=datetime.timezone.utc)),
        ),
    ]
